/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** JWKS for OAuth2 access-token signature verification */
        get: operations["getOAuthJwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/.well-known/invoice-jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * JWKS for invoice JWS signature verification (APP signing, ADR-0011)
         * @description Public keys used to sign invoices via detached JWS. Deliberately
         *     served at a separate URL from the OAuth JWKS so that invoice
         *     verifiers cannot be tricked into trusting OAuth signing keys.
         */
        get: operations["getInvoiceJwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/.well-known/oauth-authorization-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** RFC 8414 OAuth authorization-server metadata */
        get: operations["getOAuthAuthorizationServerMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Obtain an access token (OAuth2 client_credentials) */
        post: operations["createOAuthToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invoices */
        get: operations["listInvoices"];
        put?: never;
        /** Submit a single invoice for transmission to NRS */
        post: operations["submitInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit up to 500 invoices via NDJSON
         * @description Each line is a canonical Invoice document. Each row is processed
         *     through the same pipeline as `POST /v1/invoices` (validation,
         *     signing, persistence, audit, webhook publish). The response is
         *     NDJSON, one `BulkLineResult` per input line in input order. The
         *     HTTP status is `202` if every row was accepted and `207` if at
         *     least one row failed.
         */
        post: operations["submitBulkInvoices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credit-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a credit note (convenience wrapper)
         * @description Identical contract to `POST /v1/invoices` but enforces
         *     `invoice_type_code = "381"` and requires `billing_reference`
         *     before delegating to the canonical submit pipeline.
         */
        post: operations["submitCreditNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{irn}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                irn: components["parameters"]["Irn"];
            };
            cookie?: never;
        };
        /** Retrieve an invoice by IRN */
        get: operations["getInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{irn}/transmit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                irn: components["parameters"]["Irn"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually re-trigger transmission to NRS */
        post: operations["retransmitInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{irn}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                irn: components["parameters"]["Irn"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update payment status of a previously submitted invoice */
        post: operations["updateInvoiceStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{irn}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                irn: components["parameters"]["Irn"];
            };
            cookie?: never;
        };
        /**
         * Render the invoice as a PDF with embedded NRS QR
         * @description Returns an A4 PDF rendering of the canonical invoice with the
         *     NRS QR code embedded in the bottom-right. Renders are audited
         *     as `invoice.pdf_rendered`.
         */
        get: operations["renderInvoicePdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/odoo/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an Odoo account.move; Linkbridge maps it to canonical */
        post: operations["submitOdooInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook subscriptions */
        get: operations["listWebhooks"];
        put?: never;
        /**
         * Register a webhook subscription
         * @description Returns the freshly minted shared secret in the `secret` field
         *     of the response body. The secret is shown exactly once; only an
         *     Argon2id hash is persisted. To rotate, DELETE and re-create.
         */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook subscription */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue a test delivery
         * @description Enqueues a synthetic `webhook.test` event for the named
         *     subscription. The actual outbound POST happens asynchronously
         *     in the delivery worker; this endpoint returns the delivery id
         *     so callers can poll status.
         */
        post: operations["testWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lookups/tax-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List NRS tax categories
         * @description Returns the platform-wide tax category catalogue. Cacheable
         *     (`Cache-Control: public, max-age=3600, must-revalidate`); use
         *     `If-None-Match` for conditional GET — the server returns 304
         *     when the catalogue (and your filter) is unchanged.
         */
        get: operations["listTaxCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lookups/hsn-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse / search HSN product codes
         * @description Returns paged HSN catalogue rows. Use `q` for a free-text
         *     substring match on description, `prefix` for a code prefix
         *     (e.g. `85`), or `parent` to browse children of a node.
         *     Pagination is forward-only via the opaque `cursor` returned
         *     in `next_cursor`. Same caching semantics as `/tax-codes`.
         */
        get: operations["listHsnCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/crypto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report whether FIRS crypto material is configured
         * @description Returns the active Service ID and a fingerprint of the stored
         *     public key (never the private key — none is held here). Requires
         *     the `invoices:read` scope.
         */
        get: operations["getCryptoStatus"];
        /**
         * Upload / replace this tenant's FIRS crypto material
         * @description Stores the public key + certificate from the taxpayer's
         *     `crypto_keys.txt` and the FIRS-assigned Service ID. Idempotent —
         *     re-uploading overwrites the previous material. Requires the
         *     `invoices:write` scope.
         */
        put: operations["upsertCryptoMaterial"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenants (cursor-paginated) */
        get: operations["listTenants"];
        put?: never;
        /** Create a tenant */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one tenant */
        get: operations["getTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update tenant (name, kyc_status) */
        patch: operations["updateTenant"];
        trace?: never;
    };
    "/v1/admin/api-clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API clients (optionally filtered by tenant_id) */
        get: operations["listApiClients"];
        put?: never;
        /** Create API client (returns client_secret exactly once) */
        post: operations["createApiClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/api-clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an API client (toggle disabled, change scopes) */
        patch: operations["updateApiClient"];
        trace?: never;
    };
    "/v1/admin/api-clients/{id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the client_secret for an API client */
        post: operations["rotateApiClientSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
            version?: string;
            checks?: {
                [key: string]: string;
            };
        };
        Error: {
            error: {
                /** @example validation_failed */
                code: string;
                message: string;
                details?: string[];
                trace_id?: string;
            };
        };
        TokenRequest: {
            client_id: string;
            client_secret: string;
            /** @enum {string} */
            grant_type: "client_credentials";
            /** @example invoices:write invoices:read */
            scope?: string;
        };
        TokenResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @example 900 */
            expires_in: number;
            scope?: string;
        };
        /**
         * @description Canonical NRS invoice. Authoritative JSON Schema lives at
         *     `packages/schema/invoice.schema.json`; this component mirrors its
         *     public fields so generated SDKs provide a useful request type. Runtime
         *     validation still uses the authoritative JSON Schema.
         */
        Invoice: {
            /**
             * Format: uuid
             * @description Business UUID assigned by FIRS to the supplier.
             */
            business_id: string;
            /** @description Invoice Reference Number: <InvoiceNo>-<ServiceId>-<YYYYMMDD>. */
            irn: string;
            /** @enum {string} */
            invoice_kind: "B2B" | "B2C" | "B2G";
            /** Format: date */
            issue_date: string;
            /**
             * Format: date
             * @description Optional date the invoice is due for payment.
             */
            due_date?: string;
            /** @description Optional issue time (HH:MM:SS, 24-hour clock). */
            issue_time?: string;
            /**
             * @description 381 = Credit Note, 380 = Invoice, 384 = Debit Note.
             * @enum {string}
             */
            invoice_type_code: "381" | "380" | "384";
            /** @enum {string} */
            payment_status: "PENDING" | "PAID" | "PARTIALLY_PAID" | "UNPAID" | "CANCELLED";
            /** Format: date */
            tax_point_date: string;
            document_currency_code: components["schemas"]["CurrencyCode"];
            tax_currency_code: components["schemas"]["CurrencyCode"];
            /** @description Required for credit and debit notes; links to original invoices. */
            billing_reference?: components["schemas"]["BillingReference"][];
            accounting_supplier_party: components["schemas"]["Party"];
            accounting_customer_party?: components["schemas"]["Party"];
            invoice_line: components["schemas"]["InvoiceLine"][];
            tax_total: components["schemas"]["TaxTotal"][];
            legal_monetary_total: components["schemas"]["MonetaryTotal"];
        };
        /**
         * @description ISO 4217 alphabetic currency code accepted by the NRS profile.
         * @enum {string}
         */
        CurrencyCode: "NGN" | "USD" | "EUR" | "GBP" | "JPY" | "CNY" | "ZAR" | "GHS" | "XOF" | "XAF" | "CAD" | "AUD" | "CHF" | "AED" | "SAR" | "INR";
        BillingReference: {
            irn: string;
            /** Format: date */
            issue_date: string;
        };
        Party: {
            party_name: string;
            tin: string;
            /** Format: email */
            email: string;
            telephone: string;
            business_description?: string;
            postal_address: components["schemas"]["PostalAddress"];
        };
        PostalAddress: {
            street_name: string;
            city_name: string;
            postal_zone?: string;
            country: string;
        };
        InvoiceLine: {
            hsn_code: string;
            product_category: string;
            invoiced_quantity: number;
            line_extension_amount: number;
            discount_rate?: number;
            discount_amount?: number;
            fee_rate?: number;
            fee_amount?: number;
            item: components["schemas"]["InvoiceItem"];
            price: components["schemas"]["InvoicePrice"];
        };
        InvoiceItem: {
            name: string;
            description?: string;
            sellers_item_identification: string;
        };
        InvoicePrice: {
            price_amount: number;
            base_quantity: number;
            price_unit: string;
        };
        TaxTotal: {
            tax_amount: number;
            tax_subtotal: components["schemas"]["TaxSubtotal"][];
        };
        TaxSubtotal: {
            taxable_amount: number;
            tax_amount: number;
            tax_category: components["schemas"]["TaxCategory"];
        };
        TaxCategory: {
            /** @enum {string} */
            id: "STANDARD_VAT" | "ZERO_VAT" | "EXEMPT_VAT";
            percent: number;
        };
        MonetaryTotal: {
            line_extension_amount: number;
            tax_exclusive_amount: number;
            tax_inclusive_amount: number;
            payable_amount: number;
        };
        InvoiceAccepted: {
            irn: string;
            /** @example pending */
            status: string;
            /** Format: uri */
            tracking_url: string;
            /** @description Origin of the submission, e.g. 'odoo' */
            source?: string;
        };
        /**
         * @description Wrapper around an Odoo account.move record together with the
         *     resolved company, partner, and per-line product/tax metadata.
         *     The mapper at apps/api/internal/odoomap is the source of truth
         *     for the exact field shape; this schema is intentionally permissive
         *     (additionalProperties: true) because the connector evolves
         *     independently of the API surface.
         */
        OdooAccountMovePayload: {
            options: {
                /** Format: uuid */
                business_id: string;
                service_id?: string;
                default_hsn?: string;
                default_product_category?: string;
                default_country_code?: string;
                supplier_telephone_fallback?: string;
            };
            move: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        InvoiceResult: {
            irn: string;
            /** @example transmitted */
            status: string;
            /** Format: date-time */
            posting_datetime?: string;
            /** @description Base64-encoded QR payload */
            qr_code_data?: string;
            /** @description Detached JWS over canonical invoice */
            signed_jws?: string;
        };
        InvoiceRecord: components["schemas"]["InvoiceResult"] & {
            payload?: components["schemas"]["Invoice"];
            nrs_response?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        InvoicePage: {
            data: components["schemas"]["InvoiceRecord"][];
            next_cursor?: string | null;
        };
        StatusUpdate: {
            /** @enum {string} */
            payment_status: "PAID" | "PARTIALLY_PAID" | "UNPAID" | "CANCELLED";
            reference?: string;
        };
        WebhookCreate: {
            /**
             * Format: uri
             * @description HTTPS URL. http:// is rejected at registration.
             */
            url: string;
            /**
             * @description Event types to deliver. Empty array means "all events".
             *     Unknown names are rejected at registration.
             */
            events: ("invoice.submitted" | "invoice.signed" | "invoice.transmitted" | "invoice.failed" | "webhook.test")[];
            description?: string;
        };
        Webhook: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            events: string[];
            description?: string;
            active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * @description Plaintext shared secret. Returned ONLY on the create
             *     response; subsequent reads omit this field. Store it
             *     securely — to rotate, delete and re-create.
             */
            secret?: string;
        };
        WebhookList: {
            data: components["schemas"]["Webhook"][];
        };
        WebhookTestAccepted: {
            /** Format: int64 */
            delivery_id: number;
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            webhook_id: string;
            /** @example webhook.test */
            event_type: string;
            /** @example pending */
            status: string;
        };
        CryptoStatus: {
            /** @example 94ND90NR */
            service_id: string;
            /** @example true */
            configured: boolean;
            /** @description SHA-256 of the stored public key PEM (base64url). */
            public_key_fingerprint?: string;
            certificate_present?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TaxCode: {
            /** @example STANDARD_VAT */
            id: string;
            /** @example Standard VAT */
            label: string;
            /** @example 7.5 */
            percent: number;
            /** @example VAT */
            category: string;
            notes?: string;
        };
        HsnCode: {
            /** @example 8517.12 */
            code: string;
            /** @example Smartphones */
            description: string;
            section?: string;
            parent?: string | null;
        };
        HsnCodePage: {
            items: components["schemas"]["HsnCode"][];
            next_cursor: string | null;
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            name: string;
            tin: string;
            /** @enum {string} */
            kyc_status: "pending" | "verified" | "rejected" | "suspended";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TenantPage: {
            data: components["schemas"]["Tenant"][];
            next_cursor: string | null;
        };
        APIClient: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            client_id: string;
            /** @enum {string} */
            mode: "test" | "live";
            scopes: string[];
            disabled: boolean;
            /** Format: date-time */
            created_at: string;
            last_used_at?: string | null;
        };
        APIClientWithSecret: components["schemas"]["APIClient"] & {
            /** @description Cleartext client secret. Returned only once on create / rotate-secret. */
            client_secret: string;
        };
    };
    responses: {
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Token lacks required OAuth scope */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Duplicate IRN or idempotency conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation failed against NRS schema */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                /** @description Maximum requests permitted by the exhausted policy. */
                "RateLimit-Limit"?: number;
                /** @description Requests remaining in the current bucket. */
                "RateLimit-Remaining"?: number;
                /** @description Seconds until the bucket is fully replenished. */
                "RateLimit-Reset"?: number;
                /** @description Minimum seconds before retrying a rejected request. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Distributed rate limiter unavailable; request rejected fail-closed */
        RateLimiterUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Client-generated unique key (UUIDv4 recommended). */
        IdempotencyKey: string;
        Irn: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getOAuthJwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JWKS */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    getInvoiceJwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JWKS */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/jwk-set+json": {
                        [key: string]: unknown;
                    };
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    getOAuthAuthorizationServerMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    createOAuthToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                status?: "pending" | "signed" | "transmitted" | "failed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of invoices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    submitInvoice: {
        parameters: {
            query?: {
                mode?: "async" | "sync" | "dry_run";
            };
            header: {
                /** @description Client-generated unique key (UUIDv4 recommended). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invoice"];
            };
        };
        responses: {
            /** @description Synchronous transmission completed or dry-run validation succeeded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResult"];
                };
            };
            /** @description Accepted for asynchronous transmission */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    submitBulkInvoices: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated unique key (UUIDv4 recommended). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-ndjson": string;
            };
        };
        responses: {
            /** @description All rows accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                };
            };
            /** @description At least one row failed; per-row outcome in the body */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Request too large or too many rows */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    submitCreditNote: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated unique key (UUIDv4 recommended). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invoice"];
            };
        };
        responses: {
            /** @description Accepted for asynchronous transmission */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    getInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                irn: components["parameters"]["Irn"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceRecord"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    retransmitInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                irn: components["parameters"]["Irn"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Re-queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    updateInvoiceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                irn: components["parameters"]["Irn"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceRecord"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    renderInvoicePdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                irn: components["parameters"]["Irn"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    submitOdooInvoice: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated unique key (UUIDv4 recommended). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooAccountMovePayload"];
            };
        };
        responses: {
            /** @description Accepted; mapped to canonical and queued for transmission */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceAccepted"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    testWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted; queued for delivery */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookTestAccepted"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    listTaxCodes: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List */
            200: {
                headers: {
                    ETag?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxCode"][];
                };
            };
            /** @description Not Modified — client cache is current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    listHsnCodes: {
        parameters: {
            query?: {
                q?: string;
                prefix?: string;
                parent?: string;
                cursor?: string;
                limit?: number;
                include_inactive?: boolean;
            };
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page */
            200: {
                headers: {
                    ETag?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HsnCodePage"];
                };
            };
            /** @description Not Modified — client cache is current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    getCryptoStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CryptoStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    upsertCryptoMaterial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description FIRS-assigned 8-character Service ID used in the IRN.
                     * @example 94ND90NR
                     */
                    service_id: string;
                    /** @description Base64-encoded PEM public key, exactly as in crypto_keys.txt. */
                    public_key: string;
                    /** @description Certificate string from crypto_keys.txt (optional). */
                    certificate?: string;
                };
            };
        };
        responses: {
            /** @description Stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CryptoStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    listTenants: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of tenants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    tin: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Duplicate TIN */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    updateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** @enum {string} */
                    kyc_status?: "pending" | "verified" | "rejected" | "suspended";
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    listApiClients: {
        parameters: {
            query?: {
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["APIClient"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    createApiClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    tenant_id: string;
                    /**
                     * @description Credential/data mode; the server mints the matching client_id prefix.
                     * @enum {string}
                     */
                    mode: "test" | "live";
                    scopes: string[];
                };
            };
        };
        responses: {
            /** @description Created (client_secret returned in body — store it now) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIClientWithSecret"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Duplicate client_id */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    updateApiClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    disabled?: boolean;
                    scopes?: string[];
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIClient"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
    rotateApiClientSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated (new client_secret returned in body — store it now) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIClientWithSecret"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["RateLimiterUnavailable"];
        };
    };
}
